# Generated by Django 5.1.6 on 2025-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial_trading_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingpair",
            name="ask_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="bid_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="close_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="high_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="low_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="open_price",
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tradingpair",
            name="volume_24h",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
    ]
