# Generated by Django 5.1.6 on 2025-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metrics", models.JSONField()),
                ("snapshot_type", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Analytics Snapshot",
                "verbose_name_plural": "Analytics Snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("report_type", models.CharField(max_length=50)),
                ("parameters", models.JSONField(default=dict)),
                ("result_data", models.JSONField(default=dict)),
                ("file_format", models.CharField(max_length=10)),
                ("file_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Custom Report",
                "verbose_name_plural": "Custom Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("asset", models.CharField(max_length=50)),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("PRICE", "Price Movement"),
                            ("VOLUME", "Volume Trend"),
                            ("VOLATILITY", "Volatility Forecast"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prediction_value",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "time_horizon",
                    models.CharField(
                        choices=[
                            ("SHORT", "Short Term"),
                            ("MEDIUM", "Medium Term"),
                            ("LONG", "Long Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "features_used",
                    models.JSONField(help_text="Features used in prediction"),
                ),
                ("model_version", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Market Prediction",
                "verbose_name_plural": "Market Predictions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProfitLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "gross_loss",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "trading_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("market_conditions", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Profit & Loss",
                "verbose_name_plural": "Profit & Loss",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RevenueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "commission_earnings",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "spread_revenue",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "withdrawal_fees",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "other_fees",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
            options={
                "verbose_name": "Revenue Report",
                "verbose_name_plural": "Revenue Reports",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="RiskExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "total_leveraged_positions",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "max_leverage_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_margin_used",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "available_margin",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("risk_level", models.CharField(default="NORMAL", max_length=20)),
                ("exposure_by_asset", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Risk Exposure",
                "verbose_name_plural": "Risk Exposures",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("asset", models.CharField(max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("NEWS", "News Articles"),
                            ("SOCIAL", "Social Media"),
                            ("TRADING", "Trading Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "source_data",
                    models.JSONField(help_text="Raw data used for sentiment analysis"),
                ),
                ("analysis_version", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Sentiment Analysis",
                "verbose_name_plural": "Sentiment Analyses",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("component", models.CharField(max_length=50)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("LATENCY", "API Latency"),
                            ("ERROR_RATE", "Error Rate"),
                            ("LOAD", "System Load"),
                            ("MEMORY", "Memory Usage"),
                            ("CPU", "CPU Usage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(help_text="Additional monitoring details"),
                ),
            ],
            options={
                "verbose_name": "System Health",
                "verbose_name_plural": "System Health Records",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TradeAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("active_traders", models.IntegerField(default=0)),
                (
                    "trading_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("number_of_trades", models.IntegerField(default=0)),
                (
                    "average_trade_size",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("most_traded_asset", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Trade Analytics",
                "verbose_name_plural": "Trade Analytics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
