# Generated by Django 5.1.6 on 2025-02-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="marketprediction",
            index=models.Index(
                fields=["asset", "prediction_type", "time_horizon"],
                name="analytics_m_asset_e79ccc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revenuereport",
            index=models.Index(
                fields=["period", "start_time"], name="analytics_r_period_0bd56b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentimentanalysis",
            index=models.Index(
                fields=["asset", "source_type"], name="analytics_s_asset_a994eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemhealth",
            index=models.Index(
                fields=["component", "metric_type", "status"],
                name="analytics_s_compone_958ff5_idx",
            ),
        ),
    ]
